-- Point system and booking lifecycle.
-- Run after 004_agent_delivery_reliability.sql.
-- This migration is additive; it does not delete existing usage or booking data.

-- Keep the existing point tables compatible while adding audit and idempotency
-- columns. The project already uses integer user ids in these legacy tables.
CREATE TABLE IF NOT EXISTS public.user_points (
    user_id integer PRIMARY KEY REFERENCES public.users(id),
    points integer NOT NULL DEFAULT 100,
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.user_points
    ADD COLUMN IF NOT EXISTS points integer,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz;

UPDATE public.user_points
SET points = LEAST(100, GREATEST(0, COALESCE(points, 100))),
    updated_at = COALESCE(updated_at, now())
WHERE points IS NULL OR points < 0 OR points > 100 OR updated_at IS NULL;

ALTER TABLE public.user_points
    ALTER COLUMN points SET DEFAULT 100,
    ALTER COLUMN points SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_points_range_check'
          AND conrelid = 'public.user_points'::regclass
    ) THEN
        ALTER TABLE public.user_points
            ADD CONSTRAINT user_points_range_check
            CHECK (points BETWEEN 0 AND 100)
            NOT VALID;
    END IF;
END $$;

-- Every existing user receives an initial balance without overwriting a
-- balance that has already been changed.
INSERT INTO public.user_points (user_id, points, updated_at)
SELECT id, 100, now()
FROM public.users
ON CONFLICT (user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.point_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    change integer NOT NULL,
    reason text NOT NULL,
    note text,
    event_id text,
    source_type text,
    source_id bigint,
    points_before integer,
    points_after integer,
    daily_score_before integer,
    daily_score_after integer,
    score_date date,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.point_logs
    ADD COLUMN IF NOT EXISTS event_id text,
    ADD COLUMN IF NOT EXISTS source_type text,
    ADD COLUMN IF NOT EXISTS source_id bigint,
    ADD COLUMN IF NOT EXISTS points_before integer,
    ADD COLUMN IF NOT EXISTS points_after integer,
    ADD COLUMN IF NOT EXISTS daily_score_before integer,
    ADD COLUMN IF NOT EXISTS daily_score_after integer,
    ADD COLUMN IF NOT EXISTS score_date date,
    ADD COLUMN IF NOT EXISTS created_at timestamptz;

ALTER TABLE public.point_logs
    ALTER COLUMN created_at SET DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uq_point_logs_event_id
    ON public.point_logs (event_id)
    WHERE event_id IS NOT NULL AND btrim(event_id) <> '';

CREATE INDEX IF NOT EXISTS idx_point_logs_user_created
    ON public.point_logs (user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_point_logs_score_date
    ON public.point_logs (user_id, score_date DESC);

CREATE TABLE IF NOT EXISTS public.user_daily_scores (
    user_id integer NOT NULL REFERENCES public.users(id),
    score_date date NOT NULL,
    score integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    PRIMARY KEY (user_id, score_date)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_daily_scores_range_check'
          AND conrelid = 'public.user_daily_scores'::regclass
    ) THEN
        ALTER TABLE public.user_daily_scores
            ADD CONSTRAINT user_daily_scores_range_check
            CHECK (score BETWEEN 0 AND 100)
            NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_daily_scores_date
    ON public.user_daily_scores (score_date DESC, user_id);

CREATE TABLE IF NOT EXISTS public.ban_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    ban_until timestamptz NOT NULL,
    reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ban_records_user_until
    ON public.ban_records (user_id, ban_until DESC);

-- Preserve booking history instead of deleting rows on cancellation. This is
-- required for no-show deductions and future daily reports.
ALTER TABLE public.bookings
    ADD COLUMN IF NOT EXISTS status text,
    ADD COLUMN IF NOT EXISTS checked_in_at timestamptz,
    ADD COLUMN IF NOT EXISTS checked_out_at timestamptz,
    ADD COLUMN IF NOT EXISTS cancelled_at timestamptz,
    ADD COLUMN IF NOT EXISTS cancellation_reason text,
    ADD COLUMN IF NOT EXISTS no_show_at timestamptz;

UPDATE public.bookings
SET status = CASE
    WHEN status IN ('reserved', 'attended', 'completed', 'cancelled', 'no_show')
        THEN status
    ELSE 'reserved'
END
WHERE status IS NULL OR status NOT IN ('reserved', 'attended', 'completed', 'cancelled', 'no_show');

ALTER TABLE public.bookings
    ALTER COLUMN status SET DEFAULT 'reserved',
    ALTER COLUMN status SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bookings_status_check'
          AND conrelid = 'public.bookings'::regclass
    ) THEN
        ALTER TABLE public.bookings
            ADD CONSTRAINT bookings_status_check
            CHECK (status IN ('reserved', 'attended', 'completed', 'cancelled', 'no_show'))
            NOT VALID;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_bookings_status_date
    ON public.bookings (status, booking_date, end_time);
CREATE INDEX IF NOT EXISTS idx_bookings_active_slot
    ON public.bookings (lab_id, booking_date, start_time)
    WHERE status IN ('reserved', 'attended', 'completed');

-- Link an Agent session to the booking that it actually checked into.
ALTER TABLE public.lab_access_logs
    ADD COLUMN IF NOT EXISTS booking_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'lab_access_logs_booking_id_fkey'
          AND conrelid = 'public.lab_access_logs'::regclass
    ) THEN
        ALTER TABLE public.lab_access_logs
            ADD CONSTRAINT lab_access_logs_booking_id_fkey
            FOREIGN KEY (booking_id) REFERENCES public.bookings(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lab_access_logs_booking_id
    ON public.lab_access_logs (booking_id);
