-- Daily point recovery and user requests for a one-time Admin grant.
-- Run after 006_agent_policy_hardening.sql.
-- This migration is additive and does not delete existing data.

CREATE TABLE IF NOT EXISTS public.point_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    requested_points integer NOT NULL DEFAULT 10,
    status text NOT NULL DEFAULT 'pending',
    user_message text,
    admin_note text,
    reviewed_by integer REFERENCES public.users(id),
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.point_requests
    ADD COLUMN IF NOT EXISTS requested_points integer,
    ADD COLUMN IF NOT EXISTS status text,
    ADD COLUMN IF NOT EXISTS user_message text,
    ADD COLUMN IF NOT EXISTS admin_note text,
    ADD COLUMN IF NOT EXISTS reviewed_by integer,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
    ADD COLUMN IF NOT EXISTS created_at timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz;

UPDATE public.point_requests
SET requested_points = COALESCE(requested_points, 10),
    status = CASE
        WHEN status IN ('pending', 'approved', 'rejected') THEN status
        ELSE 'pending'
    END,
    created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now())
WHERE requested_points IS NULL
   OR status IS NULL
   OR status NOT IN ('pending', 'approved', 'rejected')
   OR created_at IS NULL
   OR updated_at IS NULL;

ALTER TABLE public.point_requests
    ALTER COLUMN requested_points SET DEFAULT 10,
    ALTER COLUMN requested_points SET NOT NULL,
    ALTER COLUMN status SET DEFAULT 'pending',
    ALTER COLUMN status SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT now(),
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT now(),
    ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'point_requests_status_check'
          AND conrelid = 'public.point_requests'::regclass
    ) THEN
        ALTER TABLE public.point_requests
            ADD CONSTRAINT point_requests_status_check
            CHECK (status IN ('pending', 'approved', 'rejected'))
            NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'point_requests_amount_check'
          AND conrelid = 'public.point_requests'::regclass
    ) THEN
        ALTER TABLE public.point_requests
            ADD CONSTRAINT point_requests_amount_check
            CHECK (requested_points BETWEEN 1 AND 100)
            NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'point_requests_reviewed_by_fkey'
          AND conrelid = 'public.point_requests'::regclass
    ) THEN
        ALTER TABLE public.point_requests
            ADD CONSTRAINT point_requests_reviewed_by_fkey
            FOREIGN KEY (reviewed_by) REFERENCES public.users(id);
    END IF;
END $$;

-- A user may have historical requests, but only one unresolved request at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_point_requests_pending_user
    ON public.point_requests (user_id)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_point_requests_status_created
    ON public.point_requests (status, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_point_requests_user_created
    ON public.point_requests (user_id, created_at DESC, id DESC);
